package beans;


public enum EThemeEvenement {
    SCIENCE, TECHNOLOGIE, INNOVATION, EDUCATION, SANTE,
    ENVIRONNEMENT, ASTRONOMIE, INTELLIGENCE_ARTIFICIELLE,
    ECONOMIE, PSYCHOLOGIE, HISTOIRE, MATHEMATIQUES,
    PHILOSOPHIE, ROBOTIQUE, MEDICINE, CYBERSECURITE,
    PHYSIQUE, CHIMIE, BIOLOGIE;
}
